#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ANGRA - user-controlled local model bridge for LM Studio (Windows).

Two products live in this design (kept explicit on purpose):

  A) Angra.py            - THIS file. Dependency-free Python (standard library
                           only). It is the installer, the control CLI and the
                           owner of Angra's state. It never runs a model.
  B) The generated plugin - an official LM Studio *tools provider* plugin
                           (TypeScript, runs on LM Studio's own Node runtime,
                           uses LM Studio's own @lmstudio/sdk). Angra.py writes
                           its files from templates embedded below and
                           registers it with the official `lms dev --install`.

Principle:  USER CHOOSES.  LM STUDIO RUNS THE MODELS.  ANGRA CONNECTS THEM.

Hard invariants: Angra never loads, downloads, unloads, switches or routes
models; never patches LM Studio; never performs inference; never starts a
server. The generated plugin only obtains handles for models that are already
loaded (it enumerates loaded models first) and never calls a load operation.
"""
from __future__ import annotations

import contextlib
import dataclasses
import datetime
import hashlib
import json
import logging
import logging.handlers
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

try:  # Windows-only, standard library
    import winreg  # type: ignore
except ImportError:  # pragma: no cover
    winreg = None  # type: ignore

ANGRA_VERSION = "1.0.0"
STATE_SCHEMA = 1
PLUGIN_OWNER = "angra-local"
PLUGIN_NAME = "angra-bridge"
MAX_OUT = 2_000_000

DEFAULT_SAFETY = {
    "max_active_helpers": 1,
    "parallel_helpers": False,
    "max_helper_calls_per_response": 1,
    "recursive_delegation": False,
    "max_helper_context": 4096,
    "max_helper_output": 512,
    "timeout_seconds": 90,
    "cooldown_seconds": 5,
}
DEFAULT_CONFIG = {"lms_path": None, "session_ttl_hours": 4, "color": "auto", "unicode": "auto"}

# ----------------------------------------------------------------------------
# Embedded plugin templates (Product B). Written to disk by `install`/`repair`.
# ----------------------------------------------------------------------------
PLUGIN_MANIFEST = json.dumps(
    {"type": "plugin", "runner": "node", "owner": PLUGIN_OWNER, "name": PLUGIN_NAME, "revision": 1},
    indent=2,
) + "\n"

PLUGIN_PACKAGE_JSON = json.dumps(
    {
        "name": PLUGIN_NAME,
        "version": ANGRA_VERSION,
        "private": True,
        "description": "Angra bridge: lets a primary model consult an already-loaded, user-authorized helper model.",
        "scripts": {"dev": "lms dev", "push": "lms push"},
        "dependencies": {"@lmstudio/sdk": "^1.5.0", "zod": "3.24.1"},
        "devDependencies": {"@types/node": "^20.14.8", "typescript": "^5.9.2"},
    },
    indent=2,
) + "\n"

PLUGIN_TSCONFIG = json.dumps(
    {
        "compilerOptions": {
            "target": "ES2021",
            "module": "commonjs",
            "moduleResolution": "node",
            "esModuleInterop": True,
            "strict": True,
            "skipLibCheck": True,
            "forceConsistentCasingInFileNames": True,
            "outDir": "dist",
            "rootDir": "src",
        },
        "include": ["src/**/*.ts"],
    },
    indent=2,
) + "\n"

PLUGIN_GITIGNORE = "node_modules\ndist\n.lmstudio\n"

PLUGIN_README = r'''# angra-bridge (generated by Angra.py)

Angra.py is dependency-free Python. This plugin uses LM Studio's own supported
plugin runtime (@lmstudio/sdk on LM Studio's Node).

Tools: angra_status, angra_list_loaded_models, angra_list_connections,
angra_consult_model.

This directory is owned by Angra. Do not edit it by hand: `angra repair`
regenerates it from templates. Control everything with the `angra` command.
'''

PLUGIN_INDEX_TS = r'''import { type PluginContext } from "@lmstudio/sdk";
import { toolsProvider } from "./toolsProvider";

export async function main(context: PluginContext) {
  context.withToolsProvider(toolsProvider);
}
'''

PLUGIN_TOOLS_TS = r'''import { tool, Tool, ToolsProviderController, LMStudioClient } from "@lmstudio/sdk";
import { z } from "zod";
import { appendFile, mkdir, readFile, rename, writeFile } from "fs/promises";
import { dirname } from "path";
import { ANGRA_STATE_PATH, ANGRA_LOG_PATH } from "./angraPaths";

interface Safety {
  max_active_helpers: number;
  parallel_helpers: boolean;
  max_helper_calls_per_response: number;
  recursive_delegation: boolean;
  max_helper_context: number;
  max_helper_output: number;
  timeout_seconds: number;
  cooldown_seconds: number;
}
interface Permission {
  mode?: string;
  expires_at?: number | null;
}
interface AngraState {
  primary: string | null;
  links: Record<string, string[]>;
  permissions: Record<string, Permission>;
  safety: Safety;
}

const FALLBACK_SAFETY: Safety = {
  max_active_helpers: 1,
  parallel_helpers: false,
  max_helper_calls_per_response: 1,
  recursive_delegation: false,
  max_helper_context: 4096,
  max_helper_output: 512,
  timeout_seconds: 90,
  cooldown_seconds: 5,
};

// Single-flight guard: only one helper call at a time, no parallel inference.
let busy = false;
let lastCallAt = 0;

async function logEvent(event: string, detail: Record<string, unknown>): Promise<void> {
  // Metadata only. Never log task text, context or model answers.
  try {
    await mkdir(dirname(ANGRA_LOG_PATH), { recursive: true });
    const line = JSON.stringify({ ts: new Date().toISOString(), event, ...detail }) + "\n";
    await appendFile(ANGRA_LOG_PATH, line, "utf-8");
  } catch {
    /* logging must never break a tool call */
  }
}

async function readState(): Promise<AngraState> {
  const raw = JSON.parse(await readFile(ANGRA_STATE_PATH, "utf-8"));
  return {
    primary: typeof raw.primary === "string" ? raw.primary : null,
    links: raw.links && typeof raw.links === "object" ? raw.links : {},
    permissions: raw.permissions && typeof raw.permissions === "object" ? raw.permissions : {},
    safety: { ...FALLBACK_SAFETY, ...(raw.safety ?? {}) },
  };
}

async function consumeOnce(key: string): Promise<void> {
  const raw = JSON.parse(await readFile(ANGRA_STATE_PATH, "utf-8"));
  const p = raw.permissions?.[key];
  if (!p || p.mode !== "once") {
    throw new Error("one-time permission is no longer available");
  }
  p.mode = "off";
  p.expires_at = null;
  p.consumed_at = Date.now() / 1000;
  raw.updated_at = new Date().toISOString();
  const tmp = ANGRA_STATE_PATH + ".plugin.tmp";
  await writeFile(tmp, JSON.stringify(raw, null, 2), "utf-8");
  await rename(tmp, ANGRA_STATE_PATH);
}

function permissionOk(p: Permission | undefined): { ok: boolean; mode: string } {
  const mode = (p?.mode ?? "off").toLowerCase();
  if (mode === "enabled" || mode === "once") return { ok: true, mode };
  if (mode === "session") {
    const exp = p?.expires_at;
    if (typeof exp === "number" && Date.now() / 1000 < exp) return { ok: true, mode };
    return { ok: false, mode: "session-expired" };
  }
  return { ok: false, mode };
}

function handleKeys(h: any): string[] {
  return [h?.modelKey, h?.identifier, h?.path].filter(
    (v: unknown) => typeof v === "string" && (v as string).length > 0,
  ) as string[];
}
function sameModel(h: any, key: string): boolean {
  const k = key.trim().toLowerCase();
  return handleKeys(h).some((v) => v.toLowerCase() === k);
}

// Enumerates models that are ALREADY loaded. This never loads anything.
async function listLoadedHandles(client: LMStudioClient): Promise<any[]> {
  return (await client.llm.listLoaded()) as any[];
}

function denied(reason: string, message: string, extra: Record<string, unknown> = {}) {
  return { status: "denied", reason, message, angra_inference: "none", ...extra };
}

export async function toolsProvider(ctl: ToolsProviderController) {
  const client: LMStudioClient = (ctl as any).client ?? new LMStudioClient();
  const tools: Tool[] = [];

  tools.push(
    tool({
      name: "angra_status",
      description:
        "Report Angra bridge status: the user's declared primary model, the helper links, permissions and safety limits. Read-only.",
      parameters: {},
      implementation: async () => {
        try {
          const st = await readState();
          const loaded = (await listLoadedHandles(client)).map((h) => handleKeys(h)[0]);
          return {
            status: "ok",
            primary: st.primary,
            links: st.links,
            loaded_models: loaded,
            safety: st.safety,
            note: "Angra never loads, unloads or selects models. The user controls everything.",
          };
        } catch (e) {
          return denied("state_unavailable", "Angra state is unreadable: " + String(e));
        }
      },
    }),
  );

  tools.push(
    tool({
      name: "angra_list_loaded_models",
      description:
        "List models currently loaded in LM Studio, with Angra roles (primary/helper) and whether the user authorized them. Read-only.",
      parameters: {},
      implementation: async () => {
        try {
          const st = await readState();
          const helpers = new Set(Object.values(st.links).flat());
          const out = (await listLoadedHandles(client)).map((h) => {
            const key = handleKeys(h)[0];
            const isHelper = [...helpers].some((k) => sameModel(h, k));
            const permKey = Object.keys(st.permissions).find((k) => sameModel(h, k));
            return {
              model: key,
              is_primary: st.primary ? sameModel(h, st.primary) : false,
              is_linked_helper: isHelper,
              authorized: permKey ? permissionOk(st.permissions[permKey]).ok : false,
            };
          });
          return { status: "ok", loaded: out };
        } catch (e) {
          return denied("unavailable", "Could not list loaded models: " + String(e));
        }
      },
    }),
  );

  tools.push(
    tool({
      name: "angra_list_connections",
      description:
        "List the user-defined primary -> helper connections and whether each is currently usable. Read-only.",
      parameters: {},
      implementation: async () => {
        try {
          const st = await readState();
          const handles = await listLoadedHandles(client);
          const conns: unknown[] = [];
          for (const [primary, helpers] of Object.entries(st.links)) {
            for (const helper of helpers) {
              const loaded = handles.some((h) => sameModel(h, helper));
              const permKey = Object.keys(st.permissions).find((k) => k.toLowerCase() === helper.toLowerCase());
              const perm = permissionOk(permKey ? st.permissions[permKey] : undefined);
              conns.push({
                primary,
                helper,
                helper_loaded: loaded,
                permission: perm.mode,
                state: !loaded ? "paused_not_loaded" : perm.ok ? "connected" : "linked_not_authorized",
              });
            }
          }
          return { status: "ok", connections: conns };
        } catch (e) {
          return denied("unavailable", "Could not read connections: " + String(e));
        }
      },
    }),
  );

  tools.push(
    tool({
      name: "angra_consult_model",
      description:
        "Ask ONE already-loaded, user-authorized helper model a specific question. Send only the task and the minimal relevant context, never the whole conversation. Call at most once per answer. Returns the helper's short reply for you to use in your own final answer.",
      parameters: {
        model: z.string().describe("Name/key of the helper model, exactly as the user linked it."),
        task: z.string().describe("The specific question or task for the helper."),
        context: z.string().optional().describe("Only the minimal relevant context (code excerpt, facts)."),
      },
      implementation: async ({ model, task, context }, ctx: any) => {
        const requested = String(model ?? "").trim();
        if (!requested || requested.length > 200) {
          return denied("bad_request", "Invalid model name.");
        }
        if (!String(task ?? "").trim()) {
          return denied("bad_request", "A task is required.");
        }

        let st: AngraState;
        try {
          st = await readState();
        } catch (e) {
          await logEvent("consult_denied", { reason: "state_unavailable" });
          return denied("state_unavailable", "Angra state is unreadable; failing closed.");
        }
        const safety = st.safety;

        // Anti-recursion / anti-parallel guards (v1: always enforced).
        if (busy) {
          await logEvent("consult_denied", { reason: "busy", model: requested });
          return denied("busy", "Another helper call is in progress. Parallel helper calls are disabled.");
        }
        const sinceLast = (Date.now() - lastCallAt) / 1000;
        if (lastCallAt > 0 && sinceLast < safety.cooldown_seconds) {
          await logEvent("consult_denied", { reason: "cooldown", model: requested });
          return denied(
            "cooldown",
            "Helper cooldown active (" + safety.cooldown_seconds + "s). Only one helper call per answer is allowed.",
          );
        }

        busy = true;
        try {
          if (!st.primary) {
            return denied("no_primary", "The user has not declared a primary model (angra primary <model>).");
          }

          // FIRST: enumerate models that are already loaded. SECOND: verify.
          const handles = await listLoadedHandles(client);
          const primaryLoaded = handles.some((h) => sameModel(h, st.primary as string));
          if (!primaryLoaded) {
            await logEvent("consult_denied", { reason: "primary_not_loaded", model: requested });
            return denied("primary_paused", "The declared primary model is not loaded. Connection is paused.");
          }
          const helperHandle = handles.find((h) => sameModel(h, requested));
          if (!helperHandle) {
            await logEvent("consult_denied", { reason: "not_loaded", model: requested });
            return denied(
              "not_loaded",
              "MODEL NOT LOADED. Angra will not load it. Ask the user to load it manually in LM Studio.",
            );
          }

          const linked = (st.links[st.primary] ?? []).find((k) => sameModel(helperHandle, k));
          if (!linked) {
            await logEvent("consult_denied", { reason: "not_linked", model: requested });
            return denied("not_linked", "No user-created link from the primary to this helper (angra link).");
          }
          if (sameModel(helperHandle, st.primary)) {
            return denied("self_call", "A model cannot consult itself.");
          }

          const permKey = Object.keys(st.permissions).find((k) => k.toLowerCase() === linked.toLowerCase());
          const perm = permissionOk(permKey ? st.permissions[permKey] : undefined);
          if (!perm.ok) {
            await logEvent("consult_denied", { reason: "no_permission", model: linked, mode: perm.mode });
            return denied("no_permission", "HELPER CALL DENIED: the user has not authorized this helper (angra allow).");
          }

          // Bounded context: reject instead of silently shipping more.
          const maxChars = Math.max(256, safety.max_helper_context * 4);
          const taskText = String(task);
          const ctxText = String(context ?? "");
          if (taskText.length + ctxText.length > maxChars) {
            await logEvent("consult_denied", { reason: "context_too_large", model: linked });
            return denied(
              "context_too_large",
              "Task+context exceed the helper limit (" + maxChars + " characters). Send less.",
            );
          }

          // Fail closed if a one-time permission cannot be consumed.
          if (perm.mode === "once") {
            try {
              await consumeOnce(permKey as string);
            } catch (e) {
              return denied("no_permission", "Could not consume one-time permission: " + String(e));
            }
          }

          const controller = new AbortController();
          const timer = setTimeout(() => controller.abort(), safety.timeout_seconds * 1000);
          const outer: AbortSignal | undefined = ctx?.signal;
          if (outer) outer.addEventListener("abort", () => controller.abort());

          await logEvent("consult_start", { model: linked, mode: perm.mode });
          try {
            const userContent = ctxText.trim()
              ? "Task:\n" + taskText + "\n\nRelevant context:\n" + ctxText
              : "Task:\n" + taskText;
            const result = await (helperHandle as any).respond(
              [
                {
                  role: "system",
                  content:
                    "You are a helper model consulted by another model. Answer only the specific task, concisely. Do not ask questions back.",
                },
                { role: "user", content: userContent },
              ],
              { maxTokens: safety.max_helper_output, signal: controller.signal },
            );
            lastCallAt = Date.now();
            const text = String(result?.content ?? "").slice(0, safety.max_helper_output * 8);
            await logEvent("consult_done", { model: linked, chars: text.length });
            return {
              model: linked,
              status: "completed",
              analysis: text,
              warnings: [] as string[],
              inference_owner: "LM Studio",
              angra_inference: "none",
            };
          } catch (e) {
            lastCallAt = Date.now();
            const aborted = controller.signal.aborted;
            await logEvent("consult_error", { model: linked, aborted });
            return denied(aborted ? "timeout_or_aborted" : "helper_error", aborted ? "Helper call timed out or was aborted." : "Helper call failed: " + String(e));
          } finally {
            clearTimeout(timer);
          }
        } catch (e) {
          await logEvent("consult_error", { reason: "unexpected" });
          return denied("error", "Unexpected error: " + String(e));
        } finally {
          busy = false;
        }
      },
    }),
  );

  return tools;
}
'''


def render_angra_paths_ts(home: Path) -> str:
    return (
        "// Generated by Angra.py - Angra-owned file.\n"
        "export const ANGRA_STATE_PATH: string = %s;\n"
        "export const ANGRA_LOG_PATH: string = %s;\n"
        % (json.dumps(str(home / "state.json")), json.dumps(str(home / "logs" / "plugin.log")))
    )


def plugin_files(home: Path) -> Dict[str, str]:
    return {
        "manifest.json": PLUGIN_MANIFEST,
        "package.json": PLUGIN_PACKAGE_JSON,
        "tsconfig.json": PLUGIN_TSCONFIG,
        ".gitignore": PLUGIN_GITIGNORE,
        "README.md": PLUGIN_README,
        "src/index.ts": PLUGIN_INDEX_TS,
        "src/toolsProvider.ts": PLUGIN_TOOLS_TS,
        "src/angraPaths.ts": render_angra_paths_ts(home),
    }


PLUGIN_MARKER = ".angra-owned"


# ----------------------------------------------------------------------------
# Terminal helpers
# ----------------------------------------------------------------------------
class T:
    color = False
    blocks = False
    dot = False


_COLORS = {
    "green": "32", "red": "31", "yellow": "33", "cyan": "36", "blue": "34",
    "dim": "2", "bold": "1", "grey": "90", "orange": "38;2;217;119;87",
}


def paint(text: str, *names: str) -> str:
    if not T.color:
        return text
    codes = ";".join(_COLORS[n] for n in names)
    return "\x1b[%sm%s\x1b[0m" % (codes, text)


def _can_encode(s: str) -> bool:
    try:
        s.encode(getattr(sys.stdout, "encoding", None) or "ascii")
        return True
    except (UnicodeEncodeError, LookupError):
        return False


def _enable_vt() -> bool:
    if os.name != "nt":
        return os.environ.get("TERM", "") not in ("", "dumb")
    try:
        import ctypes
        k = ctypes.windll.kernel32  # type: ignore[attr-defined]
        h = k.GetStdHandle(-11)
        mode = ctypes.c_uint32()
        if not k.GetConsoleMode(h, ctypes.byref(mode)):
            return False
        return bool(k.SetConsoleMode(h, mode.value | 0x0004))
    except Exception:
        return False


def setup_terminal(cfg: dict, force_plain: bool, force_ascii: bool) -> None:
    with contextlib.suppress(Exception):
        sys.stdout.reconfigure(errors="replace")  # type: ignore[attr-defined]
        sys.stderr.reconfigure(errors="replace")  # type: ignore[attr-defined]
    want_color = cfg.get("color", "auto") != "off" and not force_plain and "NO_COLOR" not in os.environ
    T.color = bool(want_color and sys.stdout.isatty() and _enable_vt())
    uni = cfg.get("unicode", "auto") != "off" and not force_ascii
    T.blocks = bool(uni and _can_encode("\u2588\u2580\u2584"))
    T.dot = bool(uni and _can_encode("\u25cf"))


LOGO_GRID = [
    "..XXXXXXXX..",
    "..XEXXXXEX..",
    "XXXXXXXXXXXX",
    "XXXXXXXXXXXX",
    "..XXXXXXXX..",
    "..XXXXXXXX..",
    "..X.X..X.X..",
    "..X.X..X.X..",
]
_RGB = {"X": (217, 119, 87), "E": (20, 20, 20)}


def render_logo() -> List[str]:
    """Terminal version of the Angra mark (pixel invader: 12x8 grid)."""
    lines: List[str] = []
    if not T.blocks:
        for row in LOGO_GRID:
            lines.append("".join("##" if ch == "X" else "  " for ch in row))
        return lines
    for r in range(0, len(LOGO_GRID), 2):
        s = ""
        for a, b in zip(LOGO_GRID[r], LOGO_GRID[r + 1]):
            if T.color:
                ca, cb = _RGB.get(a), _RGB.get(b)
                if ca is None and cb is None:
                    s += " "
                elif cb is None:
                    s += "\x1b[38;2;%d;%d;%dm\u2580\x1b[0m" % ca
                elif ca is None:
                    s += "\x1b[38;2;%d;%d;%dm\u2584\x1b[0m" % cb
                elif ca == cb:
                    s += "\x1b[38;2;%d;%d;%dm\u2588\x1b[0m" % ca
                else:
                    s += "\x1b[38;2;%d;%d;%dm\x1b[48;2;%d;%d;%dm\u2580\x1b[0m" % (ca + cb)
            else:
                ta, tb = a == "X", b == "X"
                s += "\u2588" if ta and tb else "\u2580" if ta else "\u2584" if tb else " "
        lines.append(s)
    return lines


def banner() -> None:
    logo = render_logo()
    side = ["", paint("A N G R A", "orange", "bold"), "Local Model Bridge for LM Studio",
            paint("v%s  |  user chooses. LM Studio runs. Angra connects." % ANGRA_VERSION, "dim")]
    if len(logo) > 4:
        side = [""] * 2 + side
    print()
    for i, ln in enumerate(logo):
        print("  " + ln + "   " + (side[i] if i < len(side) else ""))
    print()


def rule() -> str:
    return ("\u2500" if T.blocks else "-") * 56


def dot(kind: str) -> str:
    ch = "\u25cf" if T.dot else "*"
    col = {"ok": "green", "bad": "red", "warn": "yellow"}[kind]
    return paint(ch, col)


def level_tag(level: str) -> str:
    col = {"PASS": "green", "WARN": "yellow", "FAIL": "red", "SKIP": "grey"}[level]
    return paint("[%s]" % level, col)


class UserError(Exception):
    def __init__(self, title: str, lines: Optional[List[str]] = None):
        super().__init__(title)
        self.title = title
        self.lines = lines or []


def print_error(e: UserError) -> None:
    print(paint("ERROR", "red", "bold"))
    print(e.title)
    for ln in e.lines:
        print(ln)


# ----------------------------------------------------------------------------
# Paths, files, logging
# ----------------------------------------------------------------------------
def angra_home() -> Path:
    override = os.environ.get("ANGRA_HOME")
    if override:
        return Path(override)
    base = os.environ.get("LOCALAPPDATA") or str(Path.home() / "AppData" / "Local")
    return Path(base) / "Angra"


def now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".%s.tmp" % uuid.uuid4().hex[:8])
    try:
        with open(tmp, "wb") as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(str(tmp), str(path))
    finally:
        with contextlib.suppress(OSError):
            if tmp.exists():
                tmp.unlink()


def atomic_write_text(path: Path, text: str) -> None:
    atomic_write(path, text.encode("utf-8"))


def backup_file(home: Path, path: Path, stamp: str) -> Optional[Path]:
    if not path.exists():
        return None
    try:
        rel = path.relative_to(home)
    except ValueError:
        rel = Path(path.name)
    dest = home / "backups" / stamp / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(str(path), str(dest))
    return dest


log = logging.getLogger("angra")


def setup_logging(home: Path) -> None:
    try:
        (home / "logs").mkdir(parents=True, exist_ok=True)
        h = logging.handlers.RotatingFileHandler(
            str(home / "logs" / "angra.log"), maxBytes=512_000, backupCount=2, encoding="utf-8")
        h.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
        log.addHandler(h)
        log.setLevel(logging.INFO)
        log.propagate = False
    except OSError:
        log.addHandler(logging.NullHandler())


def run(cmd: List[str], timeout: int = 30, cwd: Optional[str] = None) -> Tuple[int, str, str]:
    """Run an argument-array command (never shell=True), bounded and timed out."""
    try:
        p = subprocess.run(cmd, capture_output=True, timeout=timeout, cwd=cwd,
                           shell=False, stdin=subprocess.DEVNULL)
    except FileNotFoundError:
        return 127, "", "executable not found"
    except subprocess.TimeoutExpired:
        return 124, "", "timed out after %ss" % timeout
    except OSError as e:
        return 126, "", str(e)
    return (p.returncode, p.stdout[:MAX_OUT].decode("utf-8", "replace"),
            p.stderr[:MAX_OUT].decode("utf-8", "replace"))


def parse_json_output(text: str):
    dec = json.JSONDecoder()
    tries = 0
    for i, ch in enumerate(text):
        if ch in "[{":
            tries += 1
            if tries > 50:
                break
            try:
                obj, _ = dec.raw_decode(text[i:])
                return obj
            except ValueError:
                continue
    raise ValueError("no JSON found in output")


# ----------------------------------------------------------------------------
# Config and state
# ----------------------------------------------------------------------------
def load_config(home: Path) -> dict:
    cfg = dict(DEFAULT_CONFIG)
    p = home / "config.json"
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            cfg.update({k: raw[k] for k in DEFAULT_CONFIG if k in raw})
    except (OSError, ValueError):
        pass
    return cfg


def default_state() -> dict:
    return {
        "version": ANGRA_VERSION, "schema": STATE_SCHEMA, "primary": None, "helpers": [],
        "links": {}, "permissions": {}, "safety": dict(DEFAULT_SAFETY),
        "installation": {
            "installed": False, "installed_at": None, "home": None, "plugin_dir": None,
            "plugin_registered": False, "launcher": None, "path_entry": None,
            "path_added": False, "lms_path": None,
        },
        "created_at": now_iso(), "updated_at": now_iso(),
    }


def sanitize_safety(s: object) -> dict:
    out = dict(DEFAULT_SAFETY)
    if isinstance(s, dict):
        def clamp(k: str, lo: int, hi: int) -> None:
            v = s.get(k)  # type: ignore[union-attr]
            if isinstance(v, int) and not isinstance(v, bool):
                out[k] = max(lo, min(hi, v))
        clamp("max_helper_context", 256, 32768)
        clamp("max_helper_output", 16, 4096)
        clamp("timeout_seconds", 5, 600)
        clamp("cooldown_seconds", 0, 600)
    # v1 hard invariants: cannot be relaxed through the state file.
    out["max_active_helpers"] = 1
    out["parallel_helpers"] = False
    out["max_helper_calls_per_response"] = 1
    out["recursive_delegation"] = False
    return out


def migrate_state(raw: object) -> dict:
    st = default_state()
    if not isinstance(raw, dict):
        return st
    if isinstance(raw.get("primary"), str):
        st["primary"] = raw["primary"]
    if isinstance(raw.get("links"), dict):
        st["links"] = {str(k): [str(x) for x in v] for k, v in raw["links"].items() if isinstance(v, list) and v}
    if isinstance(raw.get("permissions"), dict):
        st["permissions"] = {str(k): dict(v) for k, v in raw["permissions"].items() if isinstance(v, dict)}
    st["safety"] = sanitize_safety(raw.get("safety"))
    st["helpers"] = sorted({h for hs in st["links"].values() for h in hs})
    if isinstance(raw.get("installation"), dict):
        st["installation"].update(raw["installation"])
    for k in ("created_at", "updated_at"):
        if isinstance(raw.get(k), str):
            st[k] = raw[k]
    st["schema"] = STATE_SCHEMA
    st["version"] = ANGRA_VERSION
    return st


class Store:
    def __init__(self, path: Path):
        self.path = path

    def load(self) -> dict:
        try:
            raw = json.loads(self.path.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return default_state()
        except (OSError, ValueError):
            stamp = time.strftime("%Y%m%d-%H%M%S")
            with contextlib.suppress(OSError):
                shutil.copy2(str(self.path), str(self.path) + ".corrupt-" + stamp)
            log.warning("state file unreadable; reset (copy kept)")
            return default_state()
        return migrate_state(raw)

    def save(self, st: dict) -> None:
        st["helpers"] = sorted({h for hs in st["links"].values() for h in hs})
        st["links"] = {k: v for k, v in st["links"].items() if v}
        st["updated_at"] = now_iso()
        atomic_write_text(self.path, json.dumps(st, indent=2, ensure_ascii=False) + "\n")


# ----------------------------------------------------------------------------
# Permission and graph logic (pure, unit-testable)
# ----------------------------------------------------------------------------
def perm_effective(st: dict, key: str, now: Optional[float] = None) -> Tuple[str, bool]:
    now = time.time() if now is None else now
    p = st["permissions"].get(key) or {}
    mode = str(p.get("mode", "off")).lower()
    if mode in ("once", "enabled"):
        return mode, True
    if mode == "session":
        exp = p.get("expires_at")
        if isinstance(exp, (int, float)) and now < exp:
            return "session", True
        return "session-expired", False
    return "off", False


def graph_add_error(st: dict, primary: str, helper: str) -> Optional[str]:
    """Return why the edge primary->helper is forbidden, or None if allowed."""
    if primary == helper:
        return "A model cannot be its own helper."
    links = st["links"]
    if links.get(helper):
        return "'%s' is already a primary for other helpers. Helper chains are disabled." % helper
    if any(primary in hs for hs in links.values()):
        return "'%s' is already a helper of another primary. Helper chains are disabled." % primary
    # explicit cycle check (defence in depth)
    seen, stack = set(), [helper]
    while stack:
        n = stack.pop()
        if n == primary:
            return "This link would create a cycle."
        if n in seen:
            continue
        seen.add(n)
        stack.extend(links.get(n, []))
    return None


# ----------------------------------------------------------------------------
# LM Studio discovery (read-only, official CLI, JSON output only)
# ----------------------------------------------------------------------------
@dataclass
class Model:
    key: str
    name: str
    path: str = ""
    arch: str = ""
    params: str = ""
    size: int = 0
    loaded: bool = False
    identifiers: List[str] = field(default_factory=list)

    def aliases(self) -> set:
        a = {self.key.lower(), self.name.lower()} | {i.lower() for i in self.identifiers}
        if self.path:
            a.add(Path(self.path.replace("\\", "/")).stem.lower())
        return {x for x in a if x}


@dataclass
class Snapshot:
    models: List[Model]
    ls_ok: bool
    ps_ok: bool
    errors: List[str]


def _first(d: dict, keys: Tuple[str, ...]):
    for k in keys:
        v = d.get(k)
        if v not in (None, ""):
            return v
    return None


def _entries(obj) -> List[dict]:
    if isinstance(obj, dict):
        for k in ("models", "data", "items", "result"):
            if isinstance(obj.get(k), list):
                obj = obj[k]
                break
        else:
            return []
    return [e for e in obj if isinstance(e, dict)] if isinstance(obj, list) else []


def _is_embedding(e: dict) -> bool:
    return str(e.get("type", "")).lower().startswith("embed")


def discover(lms: Optional[str]) -> Snapshot:
    if not lms:
        return Snapshot([], False, False, ["lms CLI not found"])
    errors: List[str] = []
    models: Dict[str, Model] = {}
    by_path: Dict[str, str] = {}
    ls_ok = ps_ok = False

    rc, out, err = run([lms, "ls", "--json"], timeout=45)
    if rc == 0:
        try:
            for e in _entries(parse_json_output(out)):
                if _is_embedding(e):
                    continue
                path = str(_first(e, ("path",)) or "")
                key = str(_first(e, ("modelKey", "model_key", "key", "id")) or Path(path.replace("\\", "/")).stem)
                if not key:
                    continue
                name = str(_first(e, ("displayName", "display_name", "name")) or key)
                size = _first(e, ("sizeBytes", "size_bytes", "size")) or 0
                models[key.lower()] = Model(
                    key=key, name=name, path=path,
                    arch=str(_first(e, ("architecture", "arch")) or ""),
                    params=str(_first(e, ("paramsString", "params")) or ""),
                    size=size if isinstance(size, int) else 0)
                if path:
                    by_path[path.lower()] = key.lower()
            ls_ok = True
        except ValueError as ex:
            errors.append("lms ls --json: unreadable output (%s)" % ex)
    else:
        errors.append("lms ls --json failed: %s" % (err.strip() or out.strip() or "rc=%d" % rc)[:200])

    rc, out, err = run([lms, "ps", "--json"], timeout=30)
    if rc == 0:
        try:
            for e in _entries(parse_json_output(out)):
                if _is_embedding(e):
                    continue
                path = str(_first(e, ("path",)) or "")
                ident = str(_first(e, ("identifier", "id")) or "")
                key = str(_first(e, ("modelKey", "model_key", "key")) or ident or path)
                k = key.lower()
                if k not in models and path and path.lower() in by_path:
                    k = by_path[path.lower()]
                if k not in models:
                    name = str(_first(e, ("displayName", "display_name", "name")) or key)
                    models[k] = Model(key=key, name=name, path=path)
                m = models[k]
                m.loaded = True
                if ident and ident not in m.identifiers:
                    m.identifiers.append(ident)
            ps_ok = True
        except ValueError as ex:
            errors.append("lms ps --json: unreadable output (%s)" % ex)
    else:
        errors.append("lms ps --json failed: %s" % (err.strip() or out.strip() or "rc=%d" % rc)[:200])

    ordered = sorted(models.values(), key=lambda m: (not m.loaded, m.name.lower()))
    return Snapshot(ordered, ls_ok, ps_ok, errors)


def validate_name(name: str) -> str:
    n = (name or "").strip()
    if not n or len(n) > 200:
        raise UserError("Invalid model name.", ["Model names must be 1-200 characters."])
    if any(ord(c) < 32 for c in n) or ".." in n.replace("\\", "/").split("/") or n[0] in "/\\" or ":" in n[:2]:
        raise UserError("Invalid model name.", ["Path-like or control characters are not allowed."])
    return n


def find_lmstudio_app() -> Optional[str]:
    cands: List[Path] = []
    for env in ("LOCALAPPDATA", "ProgramFiles", "ProgramFiles(x86)"):
        v = os.environ.get(env)
        if v:
            cands.append(Path(v) / "Programs" / "LM Studio" / "LM Studio.exe")
            cands.append(Path(v) / "LM Studio" / "LM Studio.exe")
    for c in cands:
        if c.is_file():
            return str(c)
    if winreg is not None:
        for hive in (winreg.HKEY_CURRENT_USER, winreg.HKEY_LOCAL_MACHINE):
            with contextlib.suppress(OSError):
                with winreg.OpenKey(hive, r"Software\Microsoft\Windows\CurrentVersion\Uninstall") as root:
                    i = 0
                    while True:
                        try:
                            sub = winreg.EnumKey(root, i)
                        except OSError:
                            break
                        i += 1
                        with contextlib.suppress(OSError):
                            with winreg.OpenKey(root, sub) as k:
                                disp = winreg.QueryValueEx(k, "DisplayName")[0]
                                if str(disp).startswith("LM Studio"):
                                    loc = winreg.QueryValueEx(k, "InstallLocation")[0]
                                    if loc:
                                        return str(loc)
    return None


def find_lms(cfg: dict) -> Optional[str]:
    if cfg.get("lms_path") and Path(str(cfg["lms_path"])).is_file():
        return str(cfg["lms_path"])
    w = shutil.which("lms")
    if w:
        return w
    for name in ("lms.exe", "lms"):  # documented default location of the lms CLI
        c = Path.home() / ".lmstudio" / "bin" / name
        if c.is_file():
            return str(c)
    return None


def plugins_root() -> Path:
    return Path.home() / ".lmstudio" / "extensions" / "plugins"


def find_installed_plugin_dirs() -> List[Path]:
    """Read-only scan for a registered copy of our plugin (layout not assumed)."""
    root = plugins_root()
    found: List[Path] = []
    if not root.is_dir():
        return found
    base_depth = len(root.parts)
    for dp, dns, fns in os.walk(str(root)):
        if len(Path(dp).parts) - base_depth > 3:
            dns[:] = []
            continue
        dns[:] = [d for d in dns if d not in ("node_modules", "dist", ".git")]
        if "manifest.json" in fns:
            with contextlib.suppress(OSError, ValueError):
                m = json.loads((Path(dp) / "manifest.json").read_text(encoding="utf-8"))
                if m.get("name") == PLUGIN_NAME and m.get("owner") == PLUGIN_OWNER:
                    found.append(Path(dp))
    return found


# ----------------------------------------------------------------------------
# Launcher and user PATH (winreg, current user only)
# ----------------------------------------------------------------------------
def launcher_text(python_exe: str, script: Path) -> str:
    def q(p: str) -> str:
        return '"%s"' % p.replace("%", "%%")
    return ("@echo off\r\nrem ANGRA launcher - generated by Angra.py (Angra-owned file)\r\n"
            "%s %s %%*\r\nexit /b %%ERRORLEVEL%%\r\n" % (q(python_exe), q(str(script))))


def encode_launcher(text: str) -> bytes:
    try:
        return text.encode("oem", "strict")  # what cmd.exe reads batch files with
    except (LookupError, UnicodeEncodeError):
        return ("@chcp 65001 >nul\r\n" + text).encode("utf-8")


def norm_entry(p: str) -> str:
    return os.path.normcase(os.path.normpath(os.path.expandvars(p.strip()))).rstrip("\\/")


def user_path_read() -> Tuple[str, int]:
    if winreg is None:
        raise UserError("User PATH is only available on Windows.")
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_READ) as k:
        try:
            v, t = winreg.QueryValueEx(k, "Path")
            return str(v), t
        except FileNotFoundError:
            return "", winreg.REG_EXPAND_SZ


def _user_path_write(value: str, typ: int) -> None:
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_SET_VALUE) as k:  # type: ignore[union-attr]
        winreg.SetValueEx(k, "Path", 0, typ, value)  # type: ignore[union-attr]
    with contextlib.suppress(Exception):
        import ctypes
        res = ctypes.c_ulong()
        ctypes.windll.user32.SendMessageTimeoutW(  # type: ignore[attr-defined]
            0xFFFF, 0x1A, 0, "Environment", 2, 5000, ctypes.byref(res))


def user_path_has(entry: str) -> bool:
    cur, _ = user_path_read()
    return any(norm_entry(p) == norm_entry(entry) for p in cur.split(";") if p.strip())


def user_path_add(entry: str) -> bool:
    cur, typ = user_path_read()
    parts = [p for p in cur.split(";") if p.strip()]
    if any(norm_entry(p) == norm_entry(entry) for p in parts):
        return False
    parts.append(entry)
    _user_path_write(";".join(parts), typ if typ in (winreg.REG_SZ, winreg.REG_EXPAND_SZ) else winreg.REG_EXPAND_SZ)  # type: ignore[union-attr]
    return True


def user_path_remove(entry: str) -> bool:
    cur, typ = user_path_read()
    parts = [p for p in cur.split(";") if p.strip()]
    keep = [p for p in parts if norm_entry(p) != norm_entry(entry)]
    if len(keep) == len(parts):
        return False
    _user_path_write(";".join(keep), typ)
    return True


# ----------------------------------------------------------------------------
# Application object
# ----------------------------------------------------------------------------
class App:
    def __init__(self) -> None:
        self.home = angra_home()
        self.cfg = load_config(self.home)
        self.store = Store(self.home / "state.json")
        self._snap: Optional[Snapshot] = None

    @property
    def plugin_dir(self) -> Path:
        return self.home / "plugin" / PLUGIN_NAME

    @property
    def bin_dir(self) -> Path:
        return self.home / "bin"

    @property
    def launcher(self) -> Path:
        return self.bin_dir / "angra.cmd"

    @property
    def script_copy(self) -> Path:
        return self.home / "Angra.py"

    def lms(self) -> Optional[str]:
        return find_lms(self.cfg)

    def snapshot(self, refresh: bool = False) -> Snapshot:
        if self._snap is None or refresh:
            self._snap = discover(self.lms())
        return self._snap

    def state(self) -> dict:
        return self.store.load()

    def resolve(self, query: str, st: Optional[dict] = None) -> Model:
        q = validate_name(query).lower()
        snap = self.snapshot()
        exact = [m for m in snap.models if q in m.aliases()]
        if len(exact) == 1:
            return exact[0]
        part = exact or [m for m in snap.models if any(q in a for a in m.aliases())]
        if len(part) == 1:
            return part[0]
        if len(part) > 1:
            raise UserError("Ambiguous model name '%s'. Matches:" % query, ["  - " + m.name for m in part])
        if not snap.ls_ok:
            st = st or self.state()
            known = set(st["links"]) | {h for hs in st["links"].values() for h in hs} | set(st["permissions"])
            if st["primary"]:
                known.add(st["primary"])
            for k in known:
                if k.lower() == q:
                    return Model(key=k, name=k)
        lines = ["", "Available models:"] + ["  - " + m.name for m in snap.models] if snap.models else \
            ["", "No models could be discovered (is LM Studio running and lms available?)."]
        raise UserError("Unknown model '%s'." % query, lines)

    def expected_plugin_state(self) -> Tuple[List[str], List[str]]:
        """(missing, modified) among Angra-owned plugin files."""
        missing, modified = [], []
        for rel, content in plugin_files(self.home).items():
            p = self.plugin_dir / rel
            if not p.is_file():
                missing.append(rel)
            elif p.read_bytes() != content.encode("utf-8"):
                modified.append(rel)
        if not (self.plugin_dir / PLUGIN_MARKER).is_file():
            missing.append(PLUGIN_MARKER)
        return missing, modified


# ----------------------------------------------------------------------------
# Views
# ----------------------------------------------------------------------------
def link_state(st: dict, snap: Snapshot, primary: str, helper: str) -> str:
    by_key = {m.key: m for m in snap.models}
    h, p = by_key.get(helper), by_key.get(primary)
    if not (h and h.loaded) or not (p and p.loaded):
        return "PAUSED"
    return "CONNECTED" if perm_effective(st, helper)[1] else "LINKED"


def model_tags(st: dict, snap: Snapshot, m: Model) -> str:
    tags = []
    if st["primary"] == m.key:
        tags.append(paint("PRIMARY", "cyan"))
    helper_of = [p for p, hs in st["links"].items() if m.key in hs]
    if helper_of:
        tags.append(paint("HELPER", "blue"))
    if perm_effective(st, m.key)[1]:
        tags.append(paint("AUTHORIZED", "yellow"))
    for p in helper_of:
        s = link_state(st, snap, p, m.key)
        if s == "CONNECTED":
            tags.append(paint("CONNECTED", "green"))
            break
        if s == "PAUSED":
            tags.append(paint("PAUSED", "yellow"))
            break
    return "  ".join(tags)


def print_models(app: App, only_loaded: bool = False) -> None:
    st, snap = app.state(), app.snapshot()
    shown = [m for m in snap.models if m.loaded or not only_loaded]
    for e in snap.errors:
        print(paint("! " + e, "yellow"))
    if not shown:
        print("  (no models to show)")
        return
    for m in shown:
        mark = dot("ok" if m.loaded else "bad") if T.color else ("[GREEN]" if m.loaded else "[RED]  ")
        vis = 1 if T.color else 7
        label = paint("LOADED", "green") if m.loaded else paint("NOT LOADED", "red")
        extra = ("  " + paint("(%s)" % m.key, "dim")) if m.key != m.name else ""
        print("  %s %s%s" % (mark, m.name, extra))
        print("  %s %s  %s" % (" " * vis, label, model_tags(st, snap, m)))
        print()


def plugin_status(app: App, st: dict) -> Tuple[bool, str]:
    missing, modified = app.expected_plugin_state()
    if missing or modified:
        return False, "generated files need repair (%d missing, %d modified)" % (len(missing), len(modified))
    if st["installation"].get("plugin_registered") or find_installed_plugin_dirs():
        return True, "registered with LM Studio"
    return False, "generated but not registered with LM Studio"


def print_dashboard(app: App) -> None:
    st, snap = app.state(), app.snapshot(refresh=True)
    online = snap.ls_ok or snap.ps_ok
    plug_ok, plug_msg = plugin_status(app, st)
    ready = online and plug_ok
    print("  %-11s %s %s" % ("LM STUDIO", dot("ok" if online else "bad"), "ONLINE" if online else "OFFLINE / lms unavailable"))
    print("  %-11s %s %s" % ("PLUGIN", dot("ok" if plug_ok else "warn"), "INSTALLED" if plug_ok else "NOT READY - " + plug_msg))
    print("  %-11s %s %s" % ("BRIDGE", dot("ok" if ready else "warn"), "READY" if ready else "NOT READY"))
    print()
    print(paint("  MODELS", "bold"))
    print("  " + rule())
    print_models(app)


def print_links(app: App) -> None:
    st, snap = app.state(), app.snapshot()
    if not st["links"]:
        print("No links. Create one with: angra link \"<primary>\" \"<helper>\"")
        return
    names = {m.key: m.name for m in snap.models}
    for p, hs in st["links"].items():
        print(paint(names.get(p, p), "cyan") + "  (primary)")
        for i, h in enumerate(hs):
            s = link_state(st, snap, p, h)
            col = {"CONNECTED": "green", "LINKED": "yellow", "PAUSED": "yellow"}[s]
            note = {"CONNECTED": "", "LINKED": "  - not authorized (angra allow)",
                    "PAUSED": "  - PAUSED / UNAVAILABLE (model not loaded)"}[s]
            print("  %s %s  [%s]%s" % ("`--" if i == len(hs) - 1 else "|--", names.get(h, h), paint(s, col), note))


def print_permissions(app: App) -> None:
    st, snap = app.state(), app.snapshot()
    names = {m.key: m.name for m in snap.models}
    keys = sorted(set(st["permissions"]) | {h for hs in st["links"].values() for h in hs})
    if not keys:
        print("No helper permissions. Grant with: angra allow \"<model>\" [--once|--session]")
        return
    for k in keys:
        mode, ok = perm_effective(st, k)
        extra = ""
        if mode == "session":
            exp = st["permissions"][k].get("expires_at")
            extra = " (until %s)" % time.strftime("%Y-%m-%d %H:%M", time.localtime(exp))
        print("  %-32s %s%s" % (names.get(k, k), paint(mode.upper(), "green" if ok else "red"), extra))


HELP = """Usage: angra <command> [args]

  (none)                       dashboard + interactive shell
  status | models | loaded     show state / all models / loaded models
  primary "<model>"            remember your primary (does NOT switch LM Studio)
  link "<primary>" "<helper>"  create a primary -> helper link (helper must be loaded)
  unlink "<primary>" "<helper>"
  connect "<model>"            link <model> to your primary (must be loaded)
  disconnect "<model>"         remove its links and revoke permission
  allow "<model>" [--once | --session]   authorize a helper (default: enabled)
  deny "<model>"               revoke authorization
  permissions | links          show permissions / connection graph
  doctor | self-test           diagnostics (no inference is ever performed)
  install | repair | uninstall
  version | help | exit

Angra never loads, unloads, downloads or selects models. LM Studio runs them."""


# ----------------------------------------------------------------------------
# Commands
# ----------------------------------------------------------------------------
def cmd_status(app: App) -> int:
    st, snap = app.state(), app.snapshot(refresh=True)
    online = snap.ls_ok or snap.ps_ok
    plug_ok, plug_msg = plugin_status(app, st)
    print("LM Studio : %s" % ("ONLINE" if online else "OFFLINE / lms unavailable"))
    print("lms CLI   : %s" % (app.lms() or "not found"))
    print("Plugin    : %s (%s)" % ("INSTALLED" if plug_ok else "NOT READY", plug_msg))
    names = {m.key: m.name for m in snap.models}
    print("Primary   : %s" % (names.get(st["primary"], st["primary"]) if st["primary"] else "(not set)"))
    n = sum(len(v) for v in st["links"].values())
    print("Links     : %d" % n)
    s = st["safety"]
    print("Safety    : helpers=%d parallel=%s calls/response=%d recursion=%s ctx=%d out=%d timeout=%ds" % (
        s["max_active_helpers"], s["parallel_helpers"], s["max_helper_calls_per_response"],
        s["recursive_delegation"], s["max_helper_context"], s["max_helper_output"], s["timeout_seconds"]))
    print("Inference : LM Studio only. Angra inference: NONE")
    return 0


def cmd_primary(app: App, args: List[str]) -> int:
    if len(args) != 1:
        raise UserError("Usage: angra primary \"<model>\"")
    st = app.state()
    m = app.resolve(args[0], st)
    if any(m.key in hs for hs in st["links"].values()):
        raise UserError("'%s' is a helper; helper chains are disabled." % m.name,
                        ["Unlink it first if you want it to be the primary."])
    st["primary"] = m.key
    app.store.save(st)
    log.info("primary set: %s", m.key)
    print("Primary model recorded: %s" % m.name)
    print("Angra did not change anything in LM Studio. Select/load your primary there yourself.")
    if not m.loaded:
        print(paint("Note: this model is not currently loaded.", "yellow"))
    return 0


def _require_loaded(m: Model) -> None:
    if not m.loaded:
        raise UserError("REQUEST DENIED", [
            "", "%s is installed but not loaded in LM Studio." % m.name, "",
            "Angra will NOT load it automatically.", "Load the model manually in LM Studio first.",
            "Then run the command again."])


def cmd_link(app: App, args: List[str]) -> int:
    if len(args) != 2:
        raise UserError("Usage: angra link \"<primary>\" \"<helper>\"")
    st = app.state()
    p, h = app.resolve(args[0], st), app.resolve(args[1], st)
    _require_loaded(h)
    err = graph_add_error(st, p.key, h.key)
    if err:
        raise UserError("LINK REFUSED", [err])
    if h.key in st["links"].get(p.key, []):
        raise UserError("Link already exists.", ["%s -> %s" % (p.name, h.name)])
    st["links"].setdefault(p.key, []).append(h.key)
    if not st["primary"]:
        st["primary"] = p.key
    app.store.save(st)
    log.info("link added: %s -> %s", p.key, h.key)
    print("LINK CREATED\n\n  %s\n      |\n      +----> %s\n" % (p.name, h.name))
    print("Nothing was loaded or started. The helper still needs permission: angra allow \"%s\"" % h.name)
    if st["primary"] != p.key:
        print(paint("Note: your declared primary is a different model; run: angra primary \"%s\"" % p.name, "yellow"))
    return 0


def cmd_unlink(app: App, args: List[str]) -> int:
    if len(args) != 2:
        raise UserError("Usage: angra unlink \"<primary>\" \"<helper>\"")
    st = app.state()
    p, h = app.resolve(args[0], st), app.resolve(args[1], st)
    if h.key not in st["links"].get(p.key, []):
        raise UserError("No such link.", ["%s -> %s" % (p.name, h.name)])
    st["links"][p.key].remove(h.key)
    app.store.save(st)
    log.info("link removed: %s -> %s", p.key, h.key)
    print("Link removed: %s -> %s" % (p.name, h.name))
    return 0


def cmd_connect(app: App, args: List[str]) -> int:
    if len(args) != 1:
        raise UserError("Usage: angra connect \"<model>\"")
    st = app.state()
    if not st["primary"]:
        raise UserError("No primary model set.", ["Run: angra primary \"<model>\" first."])
    h = app.resolve(args[0], st)
    _require_loaded(h)
    err = graph_add_error(st, st["primary"], h.key)
    if err:
        raise UserError("CONNECTION REFUSED", [err])
    names = {m.key: m.name for m in app.snapshot().models}
    if h.key not in st["links"].get(st["primary"], []):
        st["links"].setdefault(st["primary"], []).append(h.key)
        app.store.save(st)
    log.info("connect: %s -> %s", st["primary"], h.key)
    state = "CONNECTED" if perm_effective(st, h.key)[1] else "LINKED (waiting for your permission)"
    print("CONNECTION ESTABLISHED\n\nPrimary:\n%s\n\nHelper:\n%s\n\nState:\n%s\n" % (
        names.get(st["primary"], st["primary"]), h.name, state))
    print("Inference owner: LM Studio\nAngra inference: NONE")
    if not perm_effective(st, h.key)[1]:
        print("\nAuthorize it with: angra allow \"%s\" [--once|--session]" % h.name)
    return 0


def cmd_disconnect(app: App, args: List[str]) -> int:
    if len(args) != 1:
        raise UserError("Usage: angra disconnect \"<model>\"")
    st = app.state()
    h = app.resolve(args[0], st)
    removed = 0
    for hs in st["links"].values():
        while h.key in hs:
            hs.remove(h.key)
            removed += 1
    st["permissions"].pop(h.key, None)
    app.store.save(st)
    log.info("disconnect: %s (links removed=%d)", h.key, removed)
    print("Disconnected %s (links removed: %d, permission revoked)." % (h.name, removed))
    return 0


def cmd_allow(app: App, args: List[str]) -> int:
    flags = [a for a in args if a.startswith("--")]
    rest = [a for a in args if not a.startswith("--")]
    if len(rest) != 1 or any(f not in ("--once", "--session") for f in flags) or len(flags) > 1:
        raise UserError("Usage: angra allow \"<model>\" [--once | --session]")
    st = app.state()
    m = app.resolve(rest[0], st)
    if st["primary"] == m.key:
        raise UserError("The primary model cannot be authorized as a helper.")
    if flags == ["--once"]:
        entry = {"mode": "once", "granted_at": now_iso(), "expires_at": None}
    elif flags == ["--session"]:
        ttl = float(app.cfg.get("session_ttl_hours", 4))
        entry = {"mode": "session", "granted_at": now_iso(), "expires_at": time.time() + ttl * 3600}
    else:
        entry = {"mode": "enabled", "granted_at": now_iso(), "expires_at": None}
    st["permissions"][m.key] = entry
    app.store.save(st)
    log.info("permission: %s -> %s", m.key, entry["mode"])
    print("Permission for %s: %s" % (m.name, entry["mode"].upper()))
    if entry["mode"] == "session":
        print("Valid for %s hour(s)." % app.cfg.get("session_ttl_hours", 4))
    if not any(m.key in hs for hs in st["links"].values()):
        print(paint("It is not linked yet: angra link \"<primary>\" \"%s\"" % m.name, "yellow"))
    return 0


def cmd_deny(app: App, args: List[str]) -> int:
    if len(args) != 1:
        raise UserError("Usage: angra deny \"<model>\"")
    st = app.state()
    m = app.resolve(args[0], st)
    st["permissions"][m.key] = {"mode": "off", "granted_at": None, "expires_at": None}
    app.store.save(st)
    log.info("permission: %s -> off", m.key)
    print("Permission for %s: OFF (helper calls will be DENIED)" % m.name)
    return 0


# ----------------------------------------------------------------------------
# Reports: doctor / self-test
# ----------------------------------------------------------------------------
class Report:
    def __init__(self) -> None:
        self.rows: List[Tuple[str, str, str]] = []

    def add(self, level: str, name: str, detail: str = "") -> None:
        self.rows.append((level, name, detail))

    def count(self, level: str) -> int:
        return sum(1 for r in self.rows if r[0] == level)

    def print(self) -> None:
        for level, name, detail in self.rows:
            print("%s %-22s %s" % (level_tag(level), name, detail))
        print("\n%d passed, %d warnings, %d failed" % (self.count("PASS"), self.count("WARN"), self.count("FAIL")))


def lms_dev_install_capable(lms: str) -> Tuple[bool, str]:
    rc, out, err = run([lms, "dev", "--help"], timeout=20)
    text = out + err
    if rc != 0:
        return False, "`lms dev --help` failed"
    if "--install" in text or " -i," in text or "install" in text.lower():
        return True, "`lms dev --install` available"
    return False, "`lms dev` has no install option in this version"


def run_doctor(app: App) -> Report:
    r = Report()
    r.add("PASS" if os.name == "nt" else "FAIL", "Windows", sys.platform if os.name != "nt" else "Windows detected")
    r.add("PASS" if sys.version_info >= (3, 8) else "FAIL", "Python", sys.version.split()[0])
    app_path = find_lmstudio_app()
    r.add("PASS" if app_path else "WARN", "LM Studio", app_path or "application not located (lms may still work)")
    lms = app.lms()
    if lms:
        rc, _, err = run([lms, "--help"], timeout=20)
        r.add("PASS" if rc == 0 else "FAIL", "lms CLI", lms if rc == 0 else "`lms --help` failed: " + err.strip()[:120])
    else:
        r.add("FAIL", "lms CLI", "not found. Run LM Studio once, then `lms bootstrap`")
    if lms:
        ok, msg = lms_dev_install_capable(lms)
        r.add("PASS" if ok else "WARN", "Plugin support", msg)
    else:
        r.add("FAIL", "Plugin support", "requires lms")
    st = app.state()
    ok, msg = plugin_status(app, st)
    r.add("PASS" if ok else "WARN", "Plugin installation", msg)
    snap = app.snapshot(refresh=True)
    r.add("PASS" if snap.ls_ok else "FAIL", "Model discovery",
          "%d model(s)" % len(snap.models) if snap.ls_ok else "lms ls --json unavailable")
    loaded = [m for m in snap.models if m.loaded]
    r.add("PASS" if snap.ps_ok else "WARN", "Loaded models",
          "%d loaded" % len(loaded) if snap.ps_ok else "lms ps --json unavailable (LM Studio running?)")
    dirs_ok = all(p.is_dir() for p in (app.home, app.bin_dir, app.home / "logs"))
    r.add("PASS" if dirs_ok else "WARN", "Angra directories", str(app.home))
    cfgp = app.home / "config.json"
    try:
        json.loads(cfgp.read_text(encoding="utf-8"))
        r.add("PASS", "Configuration", str(cfgp))
    except (OSError, ValueError):
        r.add("WARN", "Configuration", "missing or invalid (angra repair)")
    sp = app.store.path
    try:
        json.loads(sp.read_text(encoding="utf-8"))
        r.add("PASS", "State", "%s (schema %d)" % (sp, st["schema"]))
    except (OSError, ValueError):
        r.add("WARN", "State", "missing or invalid (angra repair)")
    exp = launcher_text(sys.executable, app.script_copy)
    if app.launcher.is_file():
        same = app.launcher.read_bytes() == encode_launcher(exp)
        r.add("PASS" if same else "WARN", "Launcher", str(app.launcher) if same else "present but modified (angra repair)")
    else:
        r.add("WARN", "Launcher", "angra.cmd missing (angra install / repair)")
    if winreg is None:
        r.add("SKIP", "PATH", "Windows only")
    else:
        try:
            has = user_path_has(str(app.bin_dir))
            r.add("PASS" if has else "WARN", "PATH", "user PATH contains launcher dir" if has else "launcher dir not on user PATH")
        except OSError as e:
            r.add("FAIL", "PATH", str(e))
    try:
        app.home.mkdir(parents=True, exist_ok=True)
        t = app.home / (".write-test-%s" % uuid.uuid4().hex[:6])
        t.write_text("x")
        t.unlink()
        r.add("PASS", "Filesystem", "Angra directory is writable")
    except OSError as e:
        r.add("FAIL", "Filesystem", str(e))
    return r


FORBIDDEN_IN_PLUGIN = (".load(", ".model(", "unload(", "lms load", "load_new_instance", "downloadModel")


def run_self_test(app: App) -> Report:
    r = Report()
    # terminal rendering
    try:
        logo = render_logo()
        r.add("PASS" if logo and len({len(l) for l in logo}) >= 1 else "FAIL", "Terminal render", "%d logo lines" % len(logo))
    except Exception as e:  # pragma: no cover
        r.add("FAIL", "Terminal render", str(e))
    # CLI + JSON + filesystem + state
    with tempfile.TemporaryDirectory(prefix="angra-selftest-") as td:
        tdp = Path(td)
        try:
            s = Store(tdp / "state.json")
            st = default_state()
            st["links"] = {"a": ["b"]}
            s.save(st)
            back = s.load()
            r.add("PASS" if back["links"] == {"a": ["b"]} and back["helpers"] == ["b"] else "FAIL", "JSON/state", "atomic write + reload")
        except Exception as e:
            r.add("FAIL", "JSON/state", str(e))
        try:
            atomic_write(tdp / "x.bin", b"1")
            atomic_write(tdp / "x.bin", b"2")
            r.add("PASS" if (tdp / "x.bin").read_bytes() == b"2" else "FAIL", "Filesystem", "atomic replace")
        except Exception as e:
            r.add("FAIL", "Filesystem", str(e))
        # plugin generation
        try:
            files = plugin_files(tdp)
            for rel, content in files.items():
                atomic_write_text(tdp / "plug" / rel, content)
            json.loads((tdp / "plug" / "manifest.json").read_text())
            json.loads((tdp / "plug" / "package.json").read_text())
            json.loads((tdp / "plug" / "tsconfig.json").read_text())
            ts = files["src/toolsProvider.ts"] + files["src/index.ts"]
            bad = [f for f in FORBIDDEN_IN_PLUGIN if f in ts]
            needed = ["listLoaded", "angra_status", "angra_list_loaded_models", "angra_list_connections", "angra_consult_model"]
            miss = [n for n in needed if n not in ts]
            if bad:
                r.add("FAIL", "Plugin generation", "forbidden call(s) present: %s" % bad)
            elif miss:
                r.add("FAIL", "Plugin generation", "missing: %s" % miss)
            else:
                r.add("PASS", "Plugin generation", "%d files, no load/unload calls" % len(files))
        except Exception as e:
            r.add("FAIL", "Plugin generation", str(e))
        try:
            lt = launcher_text("C:\\Program Files\\Python\\python.exe", Path("C:\\Users\\a b\\Angra.py"))
            ok = '"C:\\Program Files\\Python\\python.exe"' in lt and "%*" in lt and "ERRORLEVEL" in lt
            r.add("PASS" if ok else "FAIL", "Launcher", "quoting, %*, exit code")
        except Exception as e:
            r.add("FAIL", "Launcher", str(e))
    # permissions
    st = default_state()
    now = 1000.0
    st["permissions"] = {
        "on": {"mode": "enabled"}, "off": {"mode": "off"},
        "s1": {"mode": "session", "expires_at": now + 10}, "s0": {"mode": "session", "expires_at": now - 1},
        "o": {"mode": "once"},
    }
    ok = (perm_effective(st, "on", now)[1] and not perm_effective(st, "off", now)[1]
          and perm_effective(st, "s1", now)[1] and not perm_effective(st, "s0", now)[1]
          and perm_effective(st, "o", now)[1] and not perm_effective(st, "missing", now)[1])
    r.add("PASS" if ok else "FAIL", "Permissions", "off/once/session/enabled/expiry")
    # connection graph
    g = default_state()
    g["links"] = {"P": ["H"]}
    checks = [graph_add_error(g, "P", "P") is not None, graph_add_error(g, "H", "P") is not None,
              graph_add_error(g, "H", "X") is not None, graph_add_error(g, "P", "Y") is None,
              graph_add_error(g, "Q", "H") is None]
    r.add("PASS" if all(checks) else "FAIL", "Connection graph", "self-loops, cycles and chains rejected")
    # safety invariants
    sf = sanitize_safety({"parallel_helpers": True, "recursive_delegation": True, "max_active_helpers": 9,
                          "max_helper_calls_per_response": 5})
    inv = (sf["parallel_helpers"] is False and sf["recursive_delegation"] is False
           and sf["max_active_helpers"] == 1 and sf["max_helper_calls_per_response"] == 1)
    r.add("PASS" if inv else "FAIL", "Safety invariants", "parallel/recursion cannot be enabled")
    # discovery
    lms = app.lms()
    if not lms:
        for n in ("LM Studio discovery", "lms", "Model discovery", "Loaded discovery"):
            r.add("WARN", n, "lms CLI not found")
    else:
        r.add("PASS", "lms", lms)
        snap = app.snapshot(refresh=True)
        r.add("PASS" if (snap.ls_ok or snap.ps_ok) else "WARN", "LM Studio discovery",
              "reachable" if (snap.ls_ok or snap.ps_ok) else "not reachable")
        r.add("PASS" if snap.ls_ok else "WARN", "Model discovery", "%d model(s)" % len(snap.models))
        r.add("PASS" if snap.ps_ok else "WARN", "Loaded discovery", "%d loaded" % sum(m.loaded for m in snap.models))
    # PATH (read-only)
    if winreg is None:
        r.add("SKIP", "PATH", "Windows only")
    else:
        try:
            user_path_read()
            r.add("PASS", "PATH", "user PATH readable")
        except OSError as e:
            r.add("FAIL", "PATH", str(e))
    return r


# ----------------------------------------------------------------------------
# Install / repair / uninstall
# ----------------------------------------------------------------------------
def write_plugin_files(app: App, stamp: str) -> List[str]:
    """Write Angra-owned plugin files. Refuses to touch a directory Angra does not own."""
    d = app.plugin_dir
    if d.exists() and not (d / PLUGIN_MARKER).is_file() and any(d.iterdir()):
        raise UserError("Refusing to overwrite a folder Angra does not own:", ["  " + str(d)])
    d.mkdir(parents=True, exist_ok=True)
    changed: List[str] = []
    allfiles = dict(plugin_files(app.home))
    allfiles[PLUGIN_MARKER] = "angra-bridge %s\n" % ANGRA_VERSION
    for rel, content in allfiles.items():
        p = d / rel
        data = content.encode("utf-8")
        if p.is_file() and p.read_bytes() == data:
            continue
        if p.exists():
            backup_file(app.home, p, stamp)
        atomic_write(p, data)
        changed.append(rel)
    return changed


def write_launcher(app: App, stamp: str) -> bool:
    data = encode_launcher(launcher_text(sys.executable, app.script_copy))
    if app.launcher.is_file() and app.launcher.read_bytes() == data:
        return False
    if app.launcher.exists():
        backup_file(app.home, app.launcher, stamp)
    atomic_write(app.launcher, data)
    return True


def install_self(app: App, stamp: str) -> bool:
    src = Path(os.path.abspath(__file__))
    dst = app.script_copy
    with contextlib.suppress(OSError):
        if dst.exists() and os.path.samefile(str(src), str(dst)):
            return False
    data = src.read_bytes()
    if dst.is_file() and dst.read_bytes() == data:
        return False
    if dst.exists():
        backup_file(app.home, dst, stamp)
    atomic_write(dst, data)
    return True


def register_plugin(app: App, lms: str) -> Tuple[bool, str]:
    """Official mechanism: `lms dev --install` from the plugin directory."""
    cwd = str(app.plugin_dir)
    for cmd in ([lms, "dev", "--install", "-y"], [lms, "dev", "--install"]):
        rc, out, err = run(cmd, timeout=240, cwd=cwd)
        text = (out + err).strip()
        if rc == 0:
            log.info("plugin registered via: %s", " ".join(cmd[1:]))
            return True, "registered via `lms %s`" % " ".join(cmd[1:])
        if rc == 124:
            return False, "`lms dev --install` timed out (LM Studio may be waiting). Try it manually in the plugin folder."
        low = text.lower()
        if "unknown" in low or "unrecognized" in low or "invalid option" in low:
            continue
        return False, "`lms %s` failed: %s" % (" ".join(cmd[1:]), text[:300])
    return False, "`lms dev --install` rejected the options in this LM Studio version"


def cmd_install(app: App, repair: bool = False) -> int:
    if os.name != "nt":
        raise UserError("Angra install supports Windows only.",
                        ["Read-only commands (models, loaded, doctor, self-test) still run elsewhere."])
    if sys.version_info < (3, 8):
        raise UserError("Python 3.8 or newer is required.")
    banner()
    title = "REPAIR" if repair else "INSTALL"
    print(paint("ANGRA %s" % title, "bold"))
    print("  [ok] Windows / Python %s" % sys.version.split()[0])
    stamp = time.strftime("%Y%m%d-%H%M%S")
    setup_logging(app.home)
    app.home.mkdir(parents=True, exist_ok=True)
    for sub in ("bin", "logs", "backups", "plugin"):
        (app.home / sub).mkdir(parents=True, exist_ok=True)
    st = app.state()
    inst = st["installation"]
    partial = False

    lms = app.lms()
    app_path = find_lmstudio_app()
    print("  [%s] LM Studio %s" % ("ok" if app_path else "??", app_path or "application not located"))
    if not lms:
        raise UserError("The `lms` CLI was not found.", [
            "Start LM Studio once, then run `lms bootstrap` (or enable the CLI in LM Studio),",
            "and run `py Angra.py install` again."])
    rc, _, err = run([lms, "--help"], timeout=20)
    if rc != 0:
        raise UserError("`lms --help` failed.", [err.strip()[:200]])
    print("  [ok] lms CLI %s" % lms)
    inst["lms_path"] = lms

    cfgp = app.home / "config.json"
    if not cfgp.is_file():
        atomic_write_text(cfgp, json.dumps(DEFAULT_CONFIG, indent=2) + "\n")
        print("  [ok] config created")
    if install_self(app, stamp):
        print("  [ok] Angra.py copied to %s" % app.script_copy)
    changed = write_plugin_files(app, stamp)
    print("  [ok] plugin project %s (%d file(s) written)" % (app.plugin_dir, len(changed)))
    inst.update({"home": str(app.home), "plugin_dir": str(app.plugin_dir)})

    capable, msg = lms_dev_install_capable(lms)
    print("  [%s] plugin support: %s" % ("ok" if capable else "!!", msg))
    if capable and (changed or not inst.get("plugin_registered") or not repair):
        ok, detail = register_plugin(app, lms)
        inst["plugin_registered"] = ok
        print("  [%s] %s" % ("ok" if ok else "!!", detail))
        partial |= not ok
    elif not capable:
        partial = True
        print("      Fallback: run `lms dev` inside the plugin folder to load it in development mode.")

    if write_launcher(app, stamp):
        print("  [ok] launcher %s" % app.launcher)
    inst["launcher"] = str(app.launcher)
    inst["path_entry"] = str(app.bin_dir)
    try:
        if not user_path_has(str(app.bin_dir)):
            user_path_add(str(app.bin_dir))
            inst["path_added"] = True
            print("  [ok] added launcher directory to your user PATH")
        else:
            print("  [ok] launcher directory already on user PATH")
    except OSError as e:
        partial = True
        print("  [!!] could not update user PATH: %s" % e)

    if not inst.get("installed_at"):
        inst["installed_at"] = now_iso()
    inst["installed"] = True
    app.store.save(st)
    log.info("%s finished (partial=%s)", title.lower(), partial)

    cmdline = 'cmd.exe /d /s /c ""%s" version"' % app.launcher
    try:
        p = subprocess.run(cmdline, capture_output=True, timeout=30, shell=False, stdin=subprocess.DEVNULL)
        vok = p.returncode == 0 and ANGRA_VERSION.encode() in p.stdout
    except (OSError, subprocess.TimeoutExpired):
        vok = False
    print("  [%s] launcher check: `angra version`" % ("ok" if vok else "!!"))
    partial |= not vok
    print()
    rep = run_doctor(app)
    rep.print()
    print()
    if partial or rep.count("FAIL"):
        print(paint("Installation finished with issues (see above).", "yellow"))
    else:
        print(paint("Installation complete.", "green"))
    print("Open a NEW Command Prompt window (PATH changes apply to new windows), then run:  angra")
    return 2 if (partial or rep.count("FAIL")) else 0


def cmd_repair(app: App) -> int:
    if not (app.home / "state.json").exists() and not app.plugin_dir.exists():
        raise UserError("Angra is not installed.", ["Run: py Angra.py install"])
    return cmd_install(app, repair=True)


def confirm(prompt: str) -> bool:
    if not sys.stdin.isatty():
        return False
    try:
        return input(prompt).strip().lower() == "yes"
    except (EOFError, KeyboardInterrupt):
        return False


def _safe_rmtree(target: Path, must_be_inside: Path) -> bool:
    t, root = target.resolve(), must_be_inside.resolve()
    if root not in t.parents:
        return False
    shutil.rmtree(str(t), ignore_errors=True)
    return True


def cmd_uninstall(app: App) -> int:
    st = app.state()
    print(paint("ANGRA UNINSTALL", "bold"))
    print("This will remove ONLY Angra-owned items:")
    print("  - the Angra plugin (registered copy + generated project)")
    print("  - the angra.cmd launcher and the user PATH entry Angra added")
    print("  - Angra state, config, logs and backups in %s" % app.home)
    print("LM Studio, your models and other plugins are never touched.")
    if not confirm("Type YES to continue: "):
        print("Cancelled. Nothing was changed.")
        return 1
    setup_logging(app.home)
    log.info("uninstall confirmed")
    lms = app.lms()

    # Plugin: no documented uninstall command was verified, so only remove the exact
    # registered copy that matches our owner/name manifest, inside the plugins root.
    removed = 0
    for d in find_installed_plugin_dirs():
        if _safe_rmtree(d, plugins_root()):
            removed += 1
    print("  [ok] registered plugin copies removed: %d" % removed)
    if lms is None:
        print("  [--] lms not found; if the plugin still shows in LM Studio, remove it there.")

    marker_ok = (app.plugin_dir / PLUGIN_MARKER).is_file()
    if app.plugin_dir.exists():
        if marker_ok and _safe_rmtree(app.plugin_dir, app.home):
            print("  [ok] generated plugin project removed")
        else:
            print("  [!!] %s has no Angra marker; left untouched" % app.plugin_dir)
    with contextlib.suppress(OSError):
        (app.home / "plugin").rmdir()

    if app.launcher.is_file():
        app.launcher.unlink()
        print("  [ok] launcher removed")
    with contextlib.suppress(OSError):
        app.bin_dir.rmdir()

    inst = st["installation"]
    if winreg is not None and inst.get("path_added") and inst.get("path_entry"):
        try:
            if user_path_remove(str(inst["path_entry"])):
                print("  [ok] removed Angra's user PATH entry")
        except OSError as e:
            print("  [!!] could not edit user PATH: %s" % e)

    logging.shutdown()
    for h in list(log.handlers):
        log.removeHandler(h)
    for rel in ("state.json", "config.json", "Angra.py"):
        with contextlib.suppress(OSError):
            (app.home / rel).unlink()
    for name in list(os.listdir(str(app.home))) if app.home.is_dir() else []:
        if name.startswith("state.json.corrupt-") or name.startswith("state.json.") and name.endswith(".tmp"):
            with contextlib.suppress(OSError):
                (app.home / name).unlink()
    for sub in ("logs", "backups"):
        _safe_rmtree(app.home / sub, app.home) if (app.home / sub).exists() else None
    with contextlib.suppress(OSError):
        app.home.rmdir()
    print("  [ok] Angra files removed" + ("" if not app.home.exists() else " (folder kept: contains other files)"))
    print("Uninstall complete. Open a new Command Prompt window for PATH to refresh.")
    return 0


def cmd_version() -> int:
    banner()
    print("Angra %s   (schema %d)" % (ANGRA_VERSION, STATE_SCHEMA))
    return 0


# ----------------------------------------------------------------------------
# Dispatch and shell
# ----------------------------------------------------------------------------
def dispatch(app: App, argv: List[str]) -> int:
    cmd, args = argv[0].lower(), argv[1:]
    table: Dict[str, Callable[[], int]] = {
        "status": lambda: cmd_status(app),
        "models": lambda: (print_models(app), 0)[1],
        "loaded": lambda: (print_models(app, only_loaded=True), 0)[1],
        "primary": lambda: cmd_primary(app, args),
        "link": lambda: cmd_link(app, args),
        "unlink": lambda: cmd_unlink(app, args),
        "connect": lambda: cmd_connect(app, args),
        "disconnect": lambda: cmd_disconnect(app, args),
        "allow": lambda: cmd_allow(app, args),
        "deny": lambda: cmd_deny(app, args),
        "permissions": lambda: (print_permissions(app), 0)[1],
        "links": lambda: (print_links(app), 0)[1],
        "doctor": lambda: (lambda r: (r.print(), 1 if r.count("FAIL") else 0)[1])(run_doctor(app)),
        "self-test": lambda: (lambda r: (r.print(), 1 if r.count("FAIL") else 0)[1])(run_self_test(app)),
        "install": lambda: cmd_install(app),
        "repair": lambda: cmd_repair(app),
        "uninstall": lambda: cmd_uninstall(app),
        "version": cmd_version,
        "help": lambda: (print(HELP), 0)[1],
    }
    if cmd in ("exit", "quit"):
        return 0
    fn = table.get(cmd)
    if fn is None:
        raise UserError("Unknown command '%s'." % argv[0], ["Run: angra help"])
    log.info("command: %s", cmd)
    return fn()


def shell(app: App) -> int:
    prompt = paint("angra", "orange", "bold") + paint(" > ", "dim")
    while True:
        try:
            line = input(prompt)
        except (EOFError, KeyboardInterrupt):
            print()
            return 0
        line = line.strip()
        if not line:
            continue
        if line.lower().startswith("angra "):
            line = line[6:]
        try:
            parts = shlex.split(line)
        except ValueError as e:
            print("Parse error: %s" % e)
            continue
        if parts and parts[0].lower() in ("exit", "quit"):
            return 0
        try:
            dispatch(app, parts)
        except UserError as e:
            print_error(e)
        print()


def main(argv: List[str]) -> int:
    force_plain = "--no-color" in argv
    force_ascii = "--ascii" in argv
    argv = [a for a in argv if a not in ("--no-color", "--ascii")]
    app = App()
    setup_terminal(app.cfg, force_plain, force_ascii)
    if app.home.is_dir():
        setup_logging(app.home)
    try:
        if not argv:
            banner()
            print_dashboard(app)
            if sys.stdin.isatty():
                print("  Type `help` for commands, `exit` to leave.\n")
                return shell(app)
            return 0
        if argv[0] in ("-h", "--help"):
            argv = ["help"]
        return dispatch(app, argv)
    except UserError as e:
        print_error(e)
        return 1
    except KeyboardInterrupt:
        print("\nInterrupted.")
        return 130
    except BrokenPipeError:
        return 0
    except OSError as e:
        print(paint("ERROR", "red", "bold"))
        print("File or system problem: %s" % e)
        log.error("OSError: %s", e)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
